/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Banner from '../components/Banner'
import Navbar from '../components/Navbar'
import { useAuth } from '../context/UserAuthContext'



const Home: NextPage = () => {
  const { user } = useAuth();
  const router = useRouter();
  useEffect(()=>{
    if(!user) router.push("/enter")
  },[user,router.push]);
  return (
    <div  >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        

        
        <Banner />


    </div>
  )
}

export default Home
